name: site checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - name: Build site
        run: bundle exec jekyll build
      - name: Check bad links
        run: bundle exec htmlproofer --only-4xx --assume-extension .html --no-enforce-https --ignore-urls https://www.pexels.com/license/,https://www.sec.gov/,https://matr
ix.to/#/#RRA:matrix.org,https://github.com/mozilla/service-map/blob/master/models/v1/indicators/indicator.py#L61-L89 ./_site
